fence implementation for spandex l2
sld-columbia/esp pull request #109
Opened 2021-04-23 20:09 UTC by vsuresh95

2021-04-23 20:46 UTC, paulmnt requested changes
Please see the minor comments in the code. Changes look good!! Thank you!!

2021-04-23 20:46 UTC, paulmnt commented on tools/socketgen/templates/noc_interface.vhd
> +        acc_done_l2                => acc_done,
the rl input signal is connected to the same driver. I would avoid changing the interface to add the `acc_done_l2` input here

2021-04-23 20:46 UTC, paulmnt commented on rtl/caches/l2_wrapper.vhd
> +      l2_fence_ready            => fence_l2_ready,
`l2_fence_ready` is not driven when Spandex cache is not present. Please assign it to a default value in the other generate statement.

2021-04-23 20:46 UTC, paulmnt commented on rtl/caches/l2_acc_wrapper.vhd
> +    acc_done_l2               : in std_logic;
See comment below: no need to add a new signal here.

2021-04-23 20:46 UTC, paulmnt commented on rtl/caches/l2_acc_wrapper.vhd
> +      l2_fence_ready            => acc_done_l2_ready,
`acc_done_l2_ready` is not driven when Spandex cache is not present. Please drive it to a default value in the other generate statement.

2021-04-23 20:46 UTC, paulmnt commented on rtl/caches/cachepackage.vhd
> +      acc_done_l2               : in std_logic;
See comment below: no need to add new signal here.

2021-04-25 09:08 UTC, vsuresh95 commented on tools/socketgen/templates/noc_interface.vhd
> +        acc_done_l2                => acc_done,
I agree! I've removed it in the same new commit.

2021-04-25 09:09 UTC, vsuresh95 commented on rtl/caches/l2_acc_wrapper.vhd
> +    acc_done_l2               : in std_logic;
I agree! I've removed it in the same new commit.

2021-04-25 09:09 UTC, vsuresh95 commented on rtl/caches/cachepackage.vhd
> +      acc_done_l2               : in std_logic;
I agree! I've removed it in the same new commit.

2021-04-25 09:09 UTC, vsuresh95 commented on rtl/caches/l2_acc_wrapper.vhd
> +      l2_fence_ready            => acc_done_l2_ready,
Done in the new commit!

2021-04-25 09:09 UTC, vsuresh95 commented on rtl/caches/l2_wrapper.vhd
> +      l2_fence_ready            => fence_l2_ready,
Done in the new commit!

2021-04-25 09:11 UTC, vsuresh95 commented
Pushed a new commit https://github.com/sld-columbia/esp/pull/109/commits/402ac130e1d46eeef16eb89199f90ab2e271dbdc with all the requested modifications.

2021-04-26 13:34 UTC, paulmnt approved these changes

2021-04-26 21:03 UTC, paulmnt requested changes

2021-04-26 21:03 UTC, paulmnt commented on rtl/caches/l2_acc_wrapper.vhd
> +
Please add a default assignment to acc_done_l2_data to avoid inferred latch

2021-04-26 21:03 UTC, paulmnt commented on rtl/caches/l2_acc_wrapper.vhd
> +        if acc_done_l2 = '1' then
See comment below related to fences: the ready/valid protocol is not implemented correctly.
In this case, however, acc_done will not be set multiple times. So, there's no need to evaluate whether a FIFO is required.

2021-04-28 15:01 UTC, vsuresh95 commented on rtl/caches/l2_wrapper.vhd
> +      when idle =>
Implemented + `sample_fence` logic.

2021-04-28 22:18 UTC, paulmnt requested changes

2021-04-28 22:18 UTC, paulmnt commented on rtl/caches/l2_wrapper.vhd
> +  fence_update: process (clk, rst, sample_fence) is
This is a sequential process, which can only be sensitive to the clock and, in case of asynchronous reset, to the reset.
No other signals can be in this sensitivity list. Please remove sample_fence. The update, in fact, occurs only at the clock edge.

2021-04-28 22:18 UTC, paulmnt commented on rtl/caches/l2_wrapper.vhd
> +
The process is driving sample_fence, which does not have a default assignment.

2021-05-04 21:28 UTC, paulmnt approved these changes

2021-05-04 21:28 UTC, merged